version: "3"

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    image: "jupyterlab:3.9.7"
    volumes: 
      - ./src:/notebook
    container_name: jupyterlab
    restart: always
    ports: 
      - "8888:8888"
